
const verificador = async () => {
    try {
        
        


    } catch (error) {
        console.log(error)

    }
}